### ISSUE TITLE
crash on choosing interpreter (Llnux)

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_python_intel#1]
выбираю в меню interpreter:
3.8.2
2.7.6
other

выбрал- креш.
```
Python 3.8
Init: cuda_project_man
Startup: 590ms, plugins: 30ms (project_man 31ms)
Init: cuda_python_intel
Python IntelliSense:  <Python 3.8.2 in /usr>
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_python_intel/__init__.py", line 485, in select_py_interpreter
    select_env()
  File "/home/user/.config/cudatext/py/cuda_python_intel/__init__.py", line 53, in select_env
    fn = items[i]
TypeError: 'generator' object is not subscriptable
Init: cuda_addonman
```

**Comment by Alexey-T** [comment]
@OlehL

**Comment by Alexey-T** [comment]
сделал фикс. дам PR
