### ISSUE TITLE
Jedi 0.18.0 error for such autocompletion

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_python_intel#13]
CudaExt plugin src.
1st word "RLS.nnnnn", caret after 'R'.
![Screenshot from 2021-01-13 01-25-44](https://user-images.githubusercontent.com/4154978/104382020-7b4e6280-553e-11eb-9227-f1b108a35c87.png)

@OlehL @davidhalter

**Comment by Alexey-T** [comment]
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_python_intel/__init__.py", line 7, in <module>
    import jedi
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/__init__.py", line 22, in <module>
    from jedi.api import classes
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/classes.py", line 24, in <module>
    from jedi.inference.utils import unite
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/__init__.py", line 70, in <module>
    from jedi.inference import imports
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/imports.py", line 23, in <module>
    from jedi.inference import compiled
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/compiled/__init__.py", line 4, in <module>
    from jedi.inference.compiled.value import CompiledValue, CompiledName, \
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/compiled/value.py", line 13, in <module>
    from jedi.inference.filters import AbstractFilter
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/filters.py", line 17, in <module>
    from jedi.inference.names import TreeNameDefinition, ParamName, \
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/names.py", line 11, in <module>
    from jedi.inference import docstrings
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/inference/docstrings.py", line 25, in <module>
    from jedi.common import indent_block
ImportError: bad magic number in 'jedi.common': b'\x03\xf3\r\n'
```

**Comment by Alexey-T** [comment]
Removed plugin and .pyc files. installed again. no error.

**Comment by davidhalter** [comment]
Yeah this is a problem that sometimes occurs when upgrading 0.18.0+. Removing all `.pyc` files solves this.
